In [21]:
import pandas as pd
df = pd.read_csv('50_sin_nulos_ni_atipicos_MexicoCity_DistritoFederal_Mexico.csv')
df = df.drop(['Unnamed: 0'], axis = 1)
df.head(5)

,host_name,host_since,host_location,host_response_time,host_response_rate,host_is_superhost,host_neighbourhood,host_verifications,host_has_profile_pic,host_identity_verified,...,number_of_reviews_ltm,number_of_reviews_l30d,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,reviews_per_month
0,Dici,2010-06-28,"Mexico City, Mexico",a few days or more,0%,f,Not specified,"['email', 'phone', 'work_email']",t,t,...,0.0,0.0,4.80,4.90,4.90,4.80,4.78,4.90,4.80,0.41
1,Fernando,2010-08-09,"Mexico City, Mexico",within an hour,100%,t,Condesa,"['email', 'phone', 'work_email']",t,t,...,0.0,0.0,4.58,4.56,4.70,4.87,4.78,4.98,4.48,0.41
2,Nicholas,2011-01-04,"Mexico City, Mexico",within an hour,71%,t,Hipódromo,"['email', 'phone']",t,t,...,4.0,0.0,4.90,4.81,4.75,4.94,4.92,4.98,4.91,0.31
3,Trisha,2010-08-24,"Mexico City, Mexico",within a few hours,100%,t,Coyoacán,"['email', 'phone', 'work_email']",t,t,...,7.0,2.0,4.91,4.90,4.96,4.96,4.98,4.96,4.92,0.83
4,Andrea,2011-04-27,"Mexico City, Mexico",within an hour,100%,t,Polanco,"['email', 'phone']",t,t,...,0.0,0.0,4.91,5.00,5.00,5.00,4.73,4.91,4.82,0.11

In [22]:
#Cambiar boleano a numerico en  host_identity_verified, host_is_superhost y instant_bookable
df["host_identity_verified"] = df["host_identity_verified"].replace({"t": 1, "f": 0})
df["host_is_superhost"] = df["host_is_superhost"].replace({"t": 1, "f": 0})
df["host_is_superhost"] = df["host_is_superhost"].replace({"Unknown": 0})
df["instant_bookable"] = df["instant_bookable"].replace({"t": 1, "f": 0})
#Cambio a numerico por jerarquia de property_type y room_type
    # Contar frecuencia de cada tipo de propiedad
frecuencia = df['property_type'].value_counts()
frecuencia2 = df['room_type'].value_counts()
    # Crear un diccionario con los valores numéricos según la frecuencia
property_map = {tipo: idx for idx, tipo in enumerate(frecuencia.index)}
property_map2 = {tipo: idx for idx, tipo in enumerate(frecuencia2.index)}
    # Reemplazar en el DataFrame
df['property_type'] = df['property_type'].map(property_map)
df['room_type'] = df['room_type'].map(property_map2)
df.head(5)

C:\Users\lmanu\AppData\Local\Temp\ipykernel_9272\140996917.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df["host_identity_verified"] = df["host_identity_verified"].replace({"t": 1, "f": 0})
C:\Users\lmanu\AppData\Local\Temp\ipykernel_9272\140996917.py:4: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df["host_is_superhost"] = df["host_is_superhost"].replace({"Unknown": 0})
C:\Users\lmanu\AppData\Local\Temp\ipykernel_9272\140996917.py:5: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df["instant_bookable"] = df["instant_bookable"].replace({"t": 1, "f": 0})

,host_name,host_since,host_location,host_response_time,host_response_rate,host_is_superhost,host_neighbourhood,host_verifications,host_has_profile_pic,host_identity_verified,...,number_of_reviews_ltm,number_of_reviews_l30d,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,reviews_per_month
0,Dici,2010-06-28,"Mexico City, Mexico",a few days or more,0%,0,Not specified,"['email', 'phone', 'work_email']",t,1,...,0.0,0.0,4.80,4.90,4.90,4.80,4.78,4.90,4.80,0.41
1,Fernando,2010-08-09,"Mexico City, Mexico",within an hour,100%,1,Condesa,"['email', 'phone', 'work_email']",t,1,...,0.0,0.0,4.58,4.56,4.70,4.87,4.78,4.98,4.48,0.41
2,Nicholas,2011-01-04,"Mexico City, Mexico",within an hour,71%,1,Hipódromo,"['email', 'phone']",t,1,...,4.0,0.0,4.90,4.81,4.75,4.94,4.92,4.98,4.91,0.31
3,Trisha,2010-08-24,"Mexico City, Mexico",within a few hours,100%,1,Coyoacán,"['email', 'phone', 'work_email']",t,1,...,7.0,2.0,4.91,4.90,4.96,4.96,4.98,4.96,4.92,0.83
4,Andrea,2011-04-27,"Mexico City, Mexico",within an hour,100%,1,Polanco,"['email', 'phone']",t,1,...,0.0,0.0,4.91,5.00,5.00,5.00,4.73,4.91,4.82,0.11

In [23]:
#['Private room' 'Entire home/apt' 'Shared room' 'Hotel room']
filtro1 = df[df["room_type"] == 1]
filtro2 = df[df["room_type"] == 0]
filtro3 = df[df["room_type"] == 3]
filtro4 = df[df["room_type"] == 2]

In [24]:
filtro1.to_csv("Private_room.csv", index=True)
filtro2.to_csv("Entire_home_apt.csv", index=True)
filtro3.to_csv("Shared_room.csv", index=True)
filtro4.to_csv("Hotel_room.csv", index=True)

In [25]:
filtro1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 8693 entries, 5 to 26580
Data columns (total 50 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   host_name                    8693 non-null   object
 1   host_since                   8693 non-null   object
 2   host_location                8693 non-null   object
 3   host_response_time           8693 non-null   object
 4   host_response_rate           8693 non-null   object
 5   host_is_superhost            8693 non-null   int64
 6   host_neighbourhood           8693 non-null   object
 7   host_verifications           8693 non-null   object
 8   host_has_profile_pic         8693 non-null   object
 9   host_identity_verified       8693 non-null   int64
 10  neighbourhood                8693 non-null   object
 11  neighbourhood_cleansed       8693 non-null   object
 12  property_type                8693 non-null   int64
 13  room_type                    8693 non-null   int64
 14  bathrooms_text               8693 non-null   object
 15  amenities                    8693 non-null   object
 16  has_availability             8693 non-null   object
 17  first_review                 8693 non-null   object
 18  last_review                  8693 non-null   object
 19  license                      8693 non-null   object
 20  instant_bookable             8693 non-null   int64
 21  host_id                      8693 non-null   int64
 22  host_acceptance_rate         8693 non-null   float64
 23  host_total_listings_count    8693 non-null   float64
 24  latitude                     8693 non-null   float64
 25  longitude                    8693 non-null   float64
 26  accommodates                 8693 non-null   float64
 27  bathrooms                    8693 non-null   float64
 28  bedrooms                     8693 non-null   float64
 29  beds                         8693 non-null   float64
 30  price                        8693 non-null   float64
 31  minimum_nights               8693 non-null   float64
 32  maximum_nights               8693 non-null   int64
 33  minimum_nights_avg_ntm       8693 non-null   float64
 34  maximum_nights_avg_ntm       8693 non-null   float64
 35  availability_30              8693 non-null   int64
 36  availability_60              8693 non-null   int64
 37  availability_90              8693 non-null   int64
 38  availability_365             8693 non-null   int64
 39  number_of_reviews            8693 non-null   float64
 40  number_of_reviews_ltm        8693 non-null   float64
 41  number_of_reviews_l30d       8693 non-null   float64
 42  review_scores_rating         8693 non-null   float64
 43  review_scores_accuracy       8693 non-null   float64
 44  review_scores_cleanliness    8693 non-null   float64
 45  review_scores_checkin        8693 non-null   float64
 46  review_scores_communication  8693 non-null   float64
 47  review_scores_location       8693 non-null   float64
 48  review_scores_value          8693 non-null   float64
 49  reviews_per_month            8693 non-null   float64
dtypes: float64(23), int64(11), object(16)
memory usage: 3.4+ MB