In [9]:
import pandas as pd
df = pd.read_csv('50_sin_nulos_ni_atipicos_Chicago_Illinois_UnitedStates.csv')
df = df.drop(['Unnamed: 0'], axis = 1)
df.head(5)

,host_name,host_since,host_location,host_response_time,host_response_rate,host_is_superhost,host_neighbourhood,host_verifications,host_has_profile_pic,host_identity_verified,...,number_of_reviews_ltm,number_of_reviews_l30d,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,reviews_per_month
0,Rebecca,2008-08-29,No location,within an hour,100%,t,Hyde Park,"['email', 'phone']",t,t,...,19.0,1.0,4.99,4.98,4.99,4.99,4.98,4.95,4.94,2.08
1,Sarah,2009-05-19,"Chicago, IL",within an hour,100%,t,Ukrainian Village,"['email', 'phone']",t,t,...,36.0,1.0,4.71,4.85,4.57,4.91,4.87,4.90,4.75,2.94
2,At Home Inn,2009-08-21,"Chicago, IL",within an hour,94%,t,Old Town,"['email', 'phone', 'work_email']",t,t,...,30.0,4.0,4.70,4.83,4.81,4.84,4.87,4.98,4.72,0.82
3,Shay And Robert,2009-10-18,"Chicago, IL",within an hour,100%,f,Lincoln Park,"['email', 'phone']",t,t,...,1.0,0.0,4.94,4.69,5.00,5.00,5.00,5.00,4.81,0.14
4,Lauri,2009-07-25,Italy,within a few hours,100%,t,Bucktown,"['email', 'phone']",t,t,...,38.0,1.2,4.80,4.86,4.75,4.93,4.86,4.92,4.71,1.34

In [10]:
#Cambiar boleano a numerico en  host_identity_verified, host_is_superhost y instant_bookable
df["host_identity_verified"] = df["host_identity_verified"].replace({"t": 1, "f": 0})
df["host_is_superhost"] = df["host_is_superhost"].replace({"t": 1, "f": 0})
df["host_is_superhost"] = df["host_is_superhost"].replace({"Unknown": 0})
df["instant_bookable"] = df["instant_bookable"].replace({"t": 1, "f": 0})
#Cambio a numerico por jerarquia de property_type y room_type
    # Contar frecuencia de cada tipo de propiedad
frecuencia = df['property_type'].value_counts()
frecuencia2 = df['room_type'].value_counts()
    # Crear un diccionario con los valores numÃ©ricos segÃºn la frecuencia
property_map = {tipo: idx for idx, tipo in enumerate(frecuencia.index)}
property_map2 = {tipo: idx for idx, tipo in enumerate(frecuencia2.index)}
    # Reemplazar en el DataFrame
df['property_type'] = df['property_type'].map(property_map)
df['room_type'] = df['room_type'].map(property_map2)
df.head(5)

C:\Users\lmanu\AppData\Local\Temp\ipykernel_13292\140996917.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df["host_identity_verified"] = df["host_identity_verified"].replace({"t": 1, "f": 0})
C:\Users\lmanu\AppData\Local\Temp\ipykernel_13292\140996917.py:4: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df["host_is_superhost"] = df["host_is_superhost"].replace({"Unknown": 0})
C:\Users\lmanu\AppData\Local\Temp\ipykernel_13292\140996917.py:5: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df["instant_bookable"] = df["instant_bookable"].replace({"t": 1, "f": 0})

,host_name,host_since,host_location,host_response_time,host_response_rate,host_is_superhost,host_neighbourhood,host_verifications,host_has_profile_pic,host_identity_verified,...,number_of_reviews_ltm,number_of_reviews_l30d,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,reviews_per_month
0,Rebecca,2008-08-29,No location,within an hour,100%,1,Hyde Park,"['email', 'phone']",t,1,...,19.0,1.0,4.99,4.98,4.99,4.99,4.98,4.95,4.94,2.08
1,Sarah,2009-05-19,"Chicago, IL",within an hour,100%,1,Ukrainian Village,"['email', 'phone']",t,1,...,36.0,1.0,4.71,4.85,4.57,4.91,4.87,4.90,4.75,2.94
2,At Home Inn,2009-08-21,"Chicago, IL",within an hour,94%,1,Old Town,"['email', 'phone', 'work_email']",t,1,...,30.0,4.0,4.70,4.83,4.81,4.84,4.87,4.98,4.72,0.82
3,Shay And Robert,2009-10-18,"Chicago, IL",within an hour,100%,0,Lincoln Park,"['email', 'phone']",t,1,...,1.0,0.0,4.94,4.69,5.00,5.00,5.00,5.00,4.81,0.14
4,Lauri,2009-07-25,Italy,within a few hours,100%,1,Bucktown,"['email', 'phone']",t,1,...,38.0,1.2,4.80,4.86,4.75,4.93,4.86,4.92,4.71,1.34

In [11]:
#['Private room' 'Entire home/apt' 'Shared room' 'Hotel room']
filtro1 = df[df["room_type"] == 1]
filtro2 = df[df["room_type"] == 0]
filtro3 = df[df["room_type"] == 3]
filtro4 = df[df["room_type"] == 2]

In [12]:
filtro1.to_csv("Private_room.csv", index=True)
filtro2.to_csv("Entire_home_apt.csv", index=True)
filtro3.to_csv("Shared_room.csv", index=True)
filtro4.to_csv("Hotel_room.csv", index=True)

In [15]:
df.to_csv("All_rooms.csv", index=True)